// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_cs_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Status               int64    `protobuf:"zigzag64,3,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Response) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.cs.service.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.cs.service.user.Response")
	proto.RegisterType((*UserInfo)(nil), "go.micro.cs.service.user.UserInfo")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xb6, 0xfb, 0xdb, 0x8e, 0x20, 0x12, 0x54, 0xca, 0x8a, 0xb0, 0xf6, 0xb4, 0xa7, 0x08, 0xeb,
	0x03, 0xc8, 0x1e, 0x15, 0x11, 0x89, 0x78, 0x5e, 0x6a, 0x3b, 0x5b, 0x83, 0x34, 0xa9, 0x99, 0x54,
	0x9f, 0xca, 0x67, 0xf0, 0xd5, 0x24, 0xb3, 0xad, 0x78, 0xd9, 0x3d, 0x79, 0x09, 0xf3, 0x7d, 0x5f,
	0x66, 0xbe, 0xc9, 0x4c, 0xe0, 0xb4, 0x71, 0xd6, 0xdb, 0xab, 0x96, 0xd0, 0xf1, 0x21, 0x19, 0x8b,
	0xb4, 0xb2, 0xb2, 0xd6, 0x85, 0xb3, 0xb2, 0x20, 0x49, 0xe8, 0x3e, 0x74, 0x81, 0x32, 0xe8, 0xd9,
	0x1d, 0x4c, 0x15, 0xbe, 0xb7, 0x48, 0x5e, 0xdc, 0x40, 0x12, 0xa8, 0xb5, 0x36, 0x1b, 0x9b, 0x46,
	0xf3, 0x68, 0x71, 0xb8, 0xcc, 0xe4, 0xae, 0x44, 0xf9, 0x4c, 0xe8, 0x6e, 0xcd, 0xc6, 0xaa, 0xb8,
	0xed, 0xa2, 0xac, 0x82, 0x58, 0x21, 0x35, 0xd6, 0x10, 0x8a, 0x63, 0x18, 0xd6, 0x54, 0x71, 0x99,
	0x44, 0x85, 0x50, 0x9c, 0x77, 0xe5, 0x4d, 0x5e, 0x63, 0x3a, 0x60, 0x9e, 0x53, 0x1f, 0xf2, 0x1a,
	0xc5, 0x19, 0x4c, 0xc8, 0xe7, 0xbe, 0xa5, 0x74, 0x38, 0x8f, 0x16, 0x42, 0x75, 0x48, 0x9c, 0xc0,
	0xd8, 0xdb, 0x37, 0x34, 0xe9, 0x88, 0x13, 0xb6, 0x20, 0xfb, 0x8e, 0x20, 0xee, 0xfd, 0xc5, 0x11,
	0x0c, 0x74, 0xc9, 0x46, 0x43, 0x35, 0xd0, 0xe5, 0x7e, 0x9f, 0x19, 0xc4, 0x4d, 0x4e, 0xf4, 0x69,
	0x5d, 0xc9, 0x4e, 0x89, 0xfa, 0xc5, 0xc1, 0xab, 0x79, 0xb5, 0x06, 0x7b, 0x2f, 0x06, 0x7f, 0x3a,
	0x1b, 0xb3, 0x45, 0xdf, 0xd9, 0x05, 0x40, 0xe1, 0x30, 0xf7, 0x58, 0xae, 0x73, 0x9f, 0x4e, 0x58,
	0x4b, 0x3a, 0x66, 0xe5, 0x83, 0xdc, 0x36, 0x65, 0x2f, 0x4f, 0xb7, 0x72, 0xc7, 0xac, 0xfc, 0xf2,
	0x2b, 0x82, 0x51, 0x78, 0x81, 0x78, 0x84, 0xf1, 0xbd, 0xad, 0xb4, 0x11, 0x97, 0xbb, 0x47, 0xdd,
	0x2d, 0x68, 0x96, 0xed, 0xbb, 0xb2, 0x9d, 0x7b, 0x76, 0x20, 0x9e, 0xc2, 0x16, 0x2a, 0x4d, 0x1e,
	0xdd, 0xbf, 0x15, 0x7d, 0x99, 0xf0, 0x3f, 0xba, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xab, 0xab,
	0x28, 0x6b, 0x60, 0x02, 0x00, 0x00,
}
