// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_cs_service_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bytes struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{0}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Bytes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileMate struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Filesha256           string   `protobuf:"bytes,4,opt,name=filesha256,proto3" json:"filesha256,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMate) Reset()         { *m = FileMate{} }
func (m *FileMate) String() string { return proto.CompactTextString(m) }
func (*FileMate) ProtoMessage()    {}
func (*FileMate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{1}
}

func (m *FileMate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMate.Unmarshal(m, b)
}
func (m *FileMate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMate.Marshal(b, m, deterministic)
}
func (m *FileMate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMate.Merge(m, src)
}
func (m *FileMate) XXX_Size() int {
	return xxx_messageInfo_FileMate.Size(m)
}
func (m *FileMate) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMate.DiscardUnknown(m)
}

var xxx_messageInfo_FileMate proto.InternalMessageInfo

func (m *FileMate) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileMate) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileMate) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileMate) GetFilesha256() string {
	if m != nil {
		return m.Filesha256
	}
	return ""
}

func (m *FileMate) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *FileMate) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FileMate) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *FileMate) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type ChunkRequest struct {
	Filesha256           string   `protobuf:"bytes,1,opt,name=filesha256,proto3" json:"filesha256,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	UploadId             string   `protobuf:"bytes,5,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Index                int64    `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkRequest) Reset()         { *m = ChunkRequest{} }
func (m *ChunkRequest) String() string { return proto.CompactTextString(m) }
func (*ChunkRequest) ProtoMessage()    {}
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{2}
}

func (m *ChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkRequest.Unmarshal(m, b)
}
func (m *ChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkRequest.Marshal(b, m, deterministic)
}
func (m *ChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkRequest.Merge(m, src)
}
func (m *ChunkRequest) XXX_Size() int {
	return xxx_messageInfo_ChunkRequest.Size(m)
}
func (m *ChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkRequest proto.InternalMessageInfo

func (m *ChunkRequest) GetFilesha256() string {
	if m != nil {
		return m.Filesha256
	}
	return ""
}

func (m *ChunkRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ChunkRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChunkRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ChunkRequest) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *ChunkRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ChunkResponse struct {
	Filesha256           string   `protobuf:"bytes,1,opt,name=filesha256,proto3" json:"filesha256,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UploadId             string   `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkSize            int64    `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkCount           int64    `protobuf:"varint,5,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	FileName             string   `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkResponse) Reset()         { *m = ChunkResponse{} }
func (m *ChunkResponse) String() string { return proto.CompactTextString(m) }
func (*ChunkResponse) ProtoMessage()    {}
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{3}
}

func (m *ChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkResponse.Unmarshal(m, b)
}
func (m *ChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkResponse.Marshal(b, m, deterministic)
}
func (m *ChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkResponse.Merge(m, src)
}
func (m *ChunkResponse) XXX_Size() int {
	return xxx_messageInfo_ChunkResponse.Size(m)
}
func (m *ChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkResponse proto.InternalMessageInfo

func (m *ChunkResponse) GetFilesha256() string {
	if m != nil {
		return m.Filesha256
	}
	return ""
}

func (m *ChunkResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ChunkResponse) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *ChunkResponse) GetChunkSize() int64 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *ChunkResponse) GetChunkCount() int64 {
	if m != nil {
		return m.ChunkCount
	}
	return 0
}

func (m *ChunkResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type MergeRequest struct {
	UploadId             string   `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeRequest) Reset()         { *m = MergeRequest{} }
func (m *MergeRequest) String() string { return proto.CompactTextString(m) }
func (*MergeRequest) ProtoMessage()    {}
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{4}
}

func (m *MergeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeRequest.Unmarshal(m, b)
}
func (m *MergeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeRequest.Marshal(b, m, deterministic)
}
func (m *MergeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeRequest.Merge(m, src)
}
func (m *MergeRequest) XXX_Size() int {
	return xxx_messageInfo_MergeRequest.Size(m)
}
func (m *MergeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeRequest proto.InternalMessageInfo

func (m *MergeRequest) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *MergeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeletedAt struct {
	DeletedAt            int64    `protobuf:"varint,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedAt) Reset()         { *m = DeletedAt{} }
func (m *DeletedAt) String() string { return proto.CompactTextString(m) }
func (*DeletedAt) ProtoMessage()    {}
func (*DeletedAt) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{5}
}

func (m *DeletedAt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedAt.Unmarshal(m, b)
}
func (m *DeletedAt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedAt.Marshal(b, m, deterministic)
}
func (m *DeletedAt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedAt.Merge(m, src)
}
func (m *DeletedAt) XXX_Size() int {
	return xxx_messageInfo_DeletedAt.Size(m)
}
func (m *DeletedAt) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedAt.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedAt proto.InternalMessageInfo

func (m *DeletedAt) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type StreamingResponse struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Bytes)(nil), "go.micro.cs.service.upload.Bytes")
	proto.RegisterType((*FileMate)(nil), "go.micro.cs.service.upload.FileMate")
	proto.RegisterType((*ChunkRequest)(nil), "go.micro.cs.service.upload.ChunkRequest")
	proto.RegisterType((*ChunkResponse)(nil), "go.micro.cs.service.upload.ChunkResponse")
	proto.RegisterType((*MergeRequest)(nil), "go.micro.cs.service.upload.MergeRequest")
	proto.RegisterType((*DeletedAt)(nil), "go.micro.cs.service.upload.DeletedAt")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.cs.service.upload.StreamingResponse")
}

func init() {
	proto.RegisterFile("proto/upload/upload.proto", fileDescriptor_5508b024e4d0ced2)
}

var fileDescriptor_5508b024e4d0ced2 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xde, 0x69, 0xda, 0xb4, 0x39, 0x56, 0xc5, 0x41, 0x30, 0x66, 0x51, 0xd7, 0x20, 0x58, 0x05,
	0xa3, 0xac, 0xac, 0xf7, 0xeb, 0x16, 0x61, 0x2f, 0xd6, 0x8b, 0x2c, 0x2a, 0x08, 0x52, 0xb2, 0x99,
	0xb3, 0xed, 0x60, 0x9a, 0xa9, 0xc9, 0x44, 0x5c, 0x5f, 0xc9, 0x67, 0xf0, 0x69, 0x7c, 0x08, 0x6f,
	0x65, 0x7e, 0xd2, 0xa6, 0x59, 0x2d, 0x45, 0xd8, 0xab, 0xf6, 0xfc, 0x7c, 0xe7, 0x9c, 0xef, 0x3b,
	0x73, 0x02, 0x77, 0x17, 0x85, 0x90, 0xe2, 0x79, 0xb5, 0xc8, 0x44, 0xc2, 0xec, 0x4f, 0xa4, 0x7d,
	0x34, 0x98, 0x8a, 0x68, 0xce, 0xd3, 0x42, 0x44, 0x69, 0x19, 0x95, 0x58, 0x7c, 0xe5, 0x29, 0x46,
	0x26, 0x23, 0x3c, 0x80, 0xde, 0xeb, 0x0b, 0x89, 0x25, 0xf5, 0xa1, 0x9f, 0x8a, 0x5c, 0x62, 0x2e,
	0x7d, 0xb2, 0x47, 0x46, 0xc3, 0xb8, 0x36, 0x29, 0x85, 0x6e, 0xc9, 0xbf, 0xa3, 0xdf, 0xd9, 0x23,
	0x23, 0x27, 0xd6, 0xff, 0xc3, 0x5f, 0x04, 0x06, 0x6f, 0x78, 0x86, 0x27, 0x89, 0x44, 0x7a, 0x03,
	0x3a, 0x9c, 0x69, 0x94, 0x13, 0x77, 0x38, 0xa3, 0x01, 0x0c, 0xce, 0x79, 0x86, 0x79, 0x32, 0x37,
	0x20, 0x2f, 0x5e, 0xda, 0xcb, 0x62, 0xce, 0xaa, 0x18, 0xbd, 0x0f, 0xa0, 0xe2, 0xe5, 0x2c, 0xd9,
	0x3f, 0x78, 0xe5, 0x77, 0x35, 0xa2, 0xe1, 0x51, 0xf5, 0x32, 0x91, 0x26, 0x92, 0x8b, 0xdc, 0xef,
	0x99, 0x7a, 0xb5, 0x4d, 0xef, 0x01, 0xa4, 0x05, 0x26, 0x12, 0xd9, 0x24, 0x91, 0xbe, 0xab, 0xab,
	0x7a, 0xd6, 0x73, 0x28, 0x55, 0xb8, 0x5a, 0xb0, 0x3a, 0xdc, 0x37, 0x61, 0xeb, 0x31, 0x61, 0x86,
	0x19, 0xda, 0xf0, 0xc0, 0x84, 0xad, 0xe7, 0x50, 0x86, 0x3f, 0x08, 0x0c, 0x8f, 0x66, 0x55, 0xfe,
	0x39, 0xc6, 0x2f, 0x15, 0x96, 0xb2, 0x35, 0x29, 0xb9, 0x34, 0xe9, 0x5f, 0xa4, 0xa2, 0x77, 0xa0,
	0x5f, 0x95, 0x58, 0x4c, 0x38, 0xb3, 0xa4, 0x5d, 0x65, 0x1e, 0x33, 0xba, 0x0b, 0x9e, 0x82, 0x4e,
	0xb4, 0x4e, 0xdd, 0x95, 0x4e, 0x6f, 0x95, 0x4e, 0xbb, 0xe0, 0x99, 0x0d, 0x29, 0x9c, 0x25, 0x6d,
	0x1c, 0xc7, 0x8c, 0xde, 0x86, 0x1e, 0xcf, 0x19, 0x7e, 0xb3, 0x7c, 0x8d, 0x11, 0xfe, 0x24, 0x70,
	0xdd, 0x4e, 0x5b, 0x2e, 0x44, 0x5e, 0xe2, 0x7f, 0x8d, 0xbb, 0xd6, 0xd8, 0x69, 0x35, 0x56, 0x6a,
	0xab, 0x0e, 0x13, 0x0d, 0xeb, 0x5a, 0xb5, 0x95, 0xe7, 0x54, 0x61, 0x1f, 0xc0, 0x35, 0x13, 0x4e,
	0x45, 0x95, 0x4b, 0x3d, 0xb6, 0x13, 0x1b, 0xc4, 0x91, 0xf2, 0xac, 0x53, 0x76, 0xd7, 0x29, 0x87,
	0x63, 0x18, 0x9e, 0x60, 0x31, 0xc5, 0x5a, 0xec, 0xb5, 0x49, 0x48, 0x6b, 0x92, 0x86, 0xaa, 0x9d,
	0xa6, 0xaa, 0xe1, 0x53, 0xf0, 0xc6, 0xf5, 0x02, 0x5b, 0xfb, 0x25, 0xed, 0xfd, 0x3e, 0x86, 0x5b,
	0xa7, 0xb2, 0xc0, 0x64, 0xce, 0xf3, 0xe9, 0x52, 0xb4, 0x5a, 0x14, 0xb2, 0x12, 0x65, 0xff, 0xb7,
	0x03, 0xee, 0x3b, 0xdd, 0x9a, 0x32, 0x80, 0x0f, 0x05, 0x97, 0x68, 0xae, 0xe6, 0x61, 0xf4, 0xef,
	0xdb, 0x8a, 0x74, 0x4a, 0xf0, 0x6c, 0x53, 0xca, 0xa5, 0xf6, 0xe1, 0xce, 0x88, 0xbc, 0x20, 0xf4,
	0x23, 0x80, 0x3a, 0xaf, 0x31, 0xca, 0x84, 0x67, 0xf4, 0xd1, 0xa6, 0x12, 0xf5, 0x19, 0x06, 0x5b,
	0x65, 0x85, 0x3b, 0xf4, 0x0c, 0x3c, 0x65, 0xe9, 0xa7, 0x42, 0x47, 0x9b, 0x40, 0xcd, 0xb7, 0x1f,
	0x3c, 0xd9, 0x22, 0xb3, 0xe6, 0x40, 0x3f, 0x99, 0x1e, 0x7a, 0x9f, 0x9b, 0x7b, 0x34, 0x57, 0xbe,
	0x35, 0x85, 0x19, 0xdc, 0x5c, 0x52, 0x78, 0x8f, 0x05, 0x3f, 0xbf, 0xb8, 0x22, 0x22, 0x67, 0xae,
	0xfe, 0x84, 0xbe, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x95, 0x75, 0x1c, 0x5f, 0x05, 0x00,
	0x00,
}
