// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_cs_service_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bytes struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{0}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Bytes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileInfo struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{1}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type StreamingResponse struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{2}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Bytes)(nil), "go.micro.cs.service.upload.Bytes")
	proto.RegisterType((*FileInfo)(nil), "go.micro.cs.service.upload.FileInfo")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.cs.service.upload.StreamingResponse")
}

func init() {
	proto.RegisterFile("proto/upload/upload.proto", fileDescriptor_5508b024e4d0ced2)
}

var fileDescriptor_5508b024e4d0ced2 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbf, 0x4b, 0xc7, 0x30,
	0x10, 0xc5, 0x8d, 0x3f, 0x6a, 0x7b, 0xb8, 0x98, 0xa9, 0xd6, 0xa5, 0x76, 0xb1, 0x8b, 0x51, 0x14,
	0x27, 0x37, 0x07, 0xa1, 0x8b, 0x43, 0x44, 0x1c, 0x25, 0xa6, 0xd7, 0x12, 0x68, 0x72, 0x25, 0x89,
	0x82, 0xfe, 0xf5, 0x62, 0x54, 0x3a, 0x7c, 0x7f, 0x4c, 0x77, 0xf7, 0xf8, 0x3c, 0xee, 0xde, 0xc1,
	0xc9, 0xec, 0x29, 0xd2, 0xe5, 0xfb, 0x3c, 0x91, 0xea, 0xff, 0x8a, 0x48, 0x1a, 0xaf, 0x46, 0x12,
	0xd6, 0x68, 0x4f, 0x42, 0x07, 0x11, 0xd0, 0x7f, 0x18, 0x8d, 0xe2, 0x97, 0x68, 0x6e, 0xe1, 0xe0,
	0xfe, 0x33, 0x62, 0xe0, 0x25, 0x1c, 0x6a, 0x72, 0x11, 0x5d, 0x2c, 0x59, 0xcd, 0xda, 0x23, 0xf9,
	0x3f, 0x72, 0x0e, 0xfb, 0xc1, 0x7c, 0x61, 0xb9, 0x5b, 0xb3, 0x76, 0x4f, 0xa6, 0xbe, 0xb9, 0x83,
	0xfc, 0xc1, 0x4c, 0xd8, 0xb9, 0x81, 0xf8, 0x29, 0x14, 0x83, 0x99, 0xf0, 0xd5, 0x29, 0x8b, 0xc9,
	0x5b, 0xc8, 0xfc, 0x47, 0x78, 0x54, 0x16, 0xd7, 0x9a, 0xcf, 0xe1, 0xf8, 0x29, 0x7a, 0x54, 0xd6,
	0xb8, 0x51, 0x62, 0x98, 0xc9, 0x85, 0x05, 0x64, 0x0b, 0x78, 0xed, 0x20, 0x7b, 0x4e, 0x67, 0xf2,
	0x1e, 0xe0, 0xc5, 0x9b, 0x88, 0x9d, 0x55, 0x23, 0xf2, 0x33, 0xb1, 0x39, 0x91, 0x48, 0x71, 0xaa,
	0x8b, 0x6d, 0xc8, 0xca, 0xf6, 0x66, 0xa7, 0x65, 0x57, 0xec, 0x2d, 0x4b, 0xff, 0xba, 0xf9, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x84, 0x50, 0xb2, 0xc7, 0x4c, 0x01, 0x00, 0x00,
}
