// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_cs_service_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bytes struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{0}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Bytes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileMate struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Filesha256           string   `protobuf:"bytes,4,opt,name=filesha256,proto3" json:"filesha256,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMate) Reset()         { *m = FileMate{} }
func (m *FileMate) String() string { return proto.CompactTextString(m) }
func (*FileMate) ProtoMessage()    {}
func (*FileMate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{1}
}

func (m *FileMate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMate.Unmarshal(m, b)
}
func (m *FileMate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMate.Marshal(b, m, deterministic)
}
func (m *FileMate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMate.Merge(m, src)
}
func (m *FileMate) XXX_Size() int {
	return xxx_messageInfo_FileMate.Size(m)
}
func (m *FileMate) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMate.DiscardUnknown(m)
}

var xxx_messageInfo_FileMate proto.InternalMessageInfo

func (m *FileMate) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileMate) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileMate) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileMate) GetFilesha256() string {
	if m != nil {
		return m.Filesha256
	}
	return ""
}

func (m *FileMate) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *FileMate) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FileMate) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *FileMate) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type DeletedAt struct {
	DeletedAt            int64    `protobuf:"varint,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedAt) Reset()         { *m = DeletedAt{} }
func (m *DeletedAt) String() string { return proto.CompactTextString(m) }
func (*DeletedAt) ProtoMessage()    {}
func (*DeletedAt) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{2}
}

func (m *DeletedAt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedAt.Unmarshal(m, b)
}
func (m *DeletedAt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedAt.Marshal(b, m, deterministic)
}
func (m *DeletedAt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedAt.Merge(m, src)
}
func (m *DeletedAt) XXX_Size() int {
	return xxx_messageInfo_DeletedAt.Size(m)
}
func (m *DeletedAt) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedAt.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedAt proto.InternalMessageInfo

func (m *DeletedAt) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type StreamingResponse struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{3}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Bytes)(nil), "go.micro.cs.service.upload.Bytes")
	proto.RegisterType((*FileMate)(nil), "go.micro.cs.service.upload.FileMate")
	proto.RegisterType((*DeletedAt)(nil), "go.micro.cs.service.upload.DeletedAt")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.cs.service.upload.StreamingResponse")
}

func init() {
	proto.RegisterFile("proto/upload/upload.proto", fileDescriptor_5508b024e4d0ced2)
}

var fileDescriptor_5508b024e4d0ced2 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x4a, 0xf3, 0x40,
	0x14, 0xee, 0xf4, 0xde, 0xc3, 0xcf, 0x0f, 0xce, 0x2a, 0x06, 0xd4, 0x1a, 0x04, 0x8b, 0x60, 0x2a,
	0x95, 0xba, 0xaf, 0x14, 0xc1, 0x85, 0x9b, 0x88, 0x08, 0x6e, 0x64, 0x9a, 0x9c, 0xc6, 0x81, 0x24,
	0x13, 0x32, 0xa7, 0x82, 0x3e, 0xa2, 0xaf, 0xe1, 0x8b, 0x48, 0x66, 0x92, 0x56, 0x2a, 0x16, 0x57,
	0xc9, 0x77, 0x0d, 0x87, 0x2f, 0xb0, 0x9f, 0x17, 0x8a, 0xd4, 0x78, 0x95, 0x27, 0x4a, 0x44, 0xd5,
	0xc3, 0x37, 0x1c, 0x77, 0x63, 0xe5, 0xa7, 0x32, 0x2c, 0x94, 0x1f, 0x6a, 0x5f, 0x63, 0xf1, 0x2a,
	0x43, 0xf4, 0xad, 0xc3, 0x3d, 0x8a, 0x95, 0x8a, 0x13, 0x1c, 0x1b, 0xe7, 0x62, 0xb5, 0x1c, 0x93,
	0x4c, 0x51, 0x93, 0x48, 0x73, 0x1b, 0xf6, 0xa6, 0xd0, 0xb9, 0x7e, 0x23, 0xd4, 0xdc, 0x81, 0x5e,
	0xa8, 0x32, 0xc2, 0x8c, 0x1c, 0x36, 0x64, 0xa3, 0x7f, 0x41, 0x0d, 0x39, 0x87, 0xb6, 0x96, 0xef,
	0xe8, 0x34, 0x87, 0x6c, 0xd4, 0x0a, 0xcc, 0xbb, 0xf7, 0xc9, 0xa0, 0x7f, 0x23, 0x13, 0xbc, 0x13,
	0x84, 0xfc, 0x3f, 0x34, 0x65, 0x64, 0x52, 0xad, 0xa0, 0x29, 0x23, 0xee, 0x42, 0x7f, 0x29, 0x13,
	0xcc, 0x44, 0x6a, 0x43, 0x83, 0x60, 0x8d, 0xd7, 0x65, 0xad, 0x4d, 0x19, 0x3f, 0x04, 0x28, 0x75,
	0xfd, 0x22, 0x26, 0xd3, 0x2b, 0xa7, 0x6d, 0x12, 0xdf, 0x98, 0xb2, 0x2f, 0x51, 0xa1, 0x20, 0xa9,
	0x32, 0xa7, 0x63, 0xfb, 0x6a, 0xcc, 0x0f, 0x00, 0xc2, 0x02, 0x05, 0x61, 0xf4, 0x2c, 0xc8, 0xe9,
	0x9a, 0xd6, 0x41, 0xc5, 0xcc, 0xa8, 0x94, 0x57, 0x79, 0x54, 0xcb, 0x3d, 0x2b, 0x57, 0x8c, 0x95,
	0x23, 0x4c, 0xb0, 0x92, 0xfb, 0x56, 0xae, 0x98, 0x19, 0x79, 0x67, 0x30, 0x98, 0xd7, 0x60, 0xcb,
	0xcb, 0xb6, 0xbd, 0xa7, 0xb0, 0x77, 0x4f, 0x05, 0x8a, 0x54, 0x66, 0x71, 0x80, 0x3a, 0x57, 0x99,
	0xde, 0x5c, 0xcb, 0x36, 0xd7, 0x4e, 0x3e, 0x18, 0x74, 0x1f, 0xcc, 0x3a, 0x3c, 0x02, 0x78, 0x2c,
	0x24, 0xe1, 0x6d, 0x2a, 0x62, 0xe4, 0xc7, 0xfe, 0xef, 0x43, 0xfa, 0x66, 0x24, 0xf7, 0x7c, 0x97,
	0xe5, 0xc7, 0xe7, 0xbd, 0xc6, 0x88, 0x5d, 0x30, 0xfe, 0x04, 0x50, 0x4e, 0x35, 0x47, 0x12, 0x32,
	0xe1, 0x27, 0xbb, 0x2a, 0xea, 0x49, 0xdd, 0x3f, 0xb9, 0xbc, 0xc6, 0xa2, 0x6b, 0xfe, 0xa2, 0xcb,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xa9, 0x72, 0xa1, 0x9f, 0x02, 0x00, 0x00,
}
