// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_cs_service_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Upload service

func NewUploadEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Upload service

type UploadService interface {
	WriteImage(ctx context.Context, opts ...client.CallOption) (Upload_WriteImageService, error)
	FileDetail(ctx context.Context, in *FileMate, opts ...client.CallOption) (*FileMate, error)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) WriteImage(ctx context.Context, opts ...client.CallOption) (Upload_WriteImageService, error) {
	req := c.c.NewRequest(c.name, "Upload.WriteImage", &Bytes{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &uploadServiceWriteImage{stream}, nil
}

type Upload_WriteImageService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Bytes) error
	Recv() (*StreamingResponse, error)
}

type uploadServiceWriteImage struct {
	stream client.Stream
}

func (x *uploadServiceWriteImage) Close() error {
	return x.stream.Close()
}

func (x *uploadServiceWriteImage) Context() context.Context {
	return x.stream.Context()
}

func (x *uploadServiceWriteImage) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadServiceWriteImage) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadServiceWriteImage) Send(m *Bytes) error {
	return x.stream.Send(m)
}

func (x *uploadServiceWriteImage) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uploadService) FileDetail(ctx context.Context, in *FileMate, opts ...client.CallOption) (*FileMate, error) {
	req := c.c.NewRequest(c.name, "Upload.FileDetail", in)
	out := new(FileMate)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Upload service

type UploadHandler interface {
	WriteImage(context.Context, Upload_WriteImageStream) error
	FileDetail(context.Context, *FileMate, *FileMate) error
}

func RegisterUploadHandler(s server.Server, hdlr UploadHandler, opts ...server.HandlerOption) error {
	type upload interface {
		WriteImage(ctx context.Context, stream server.Stream) error
		FileDetail(ctx context.Context, in *FileMate, out *FileMate) error
	}
	type Upload struct {
		upload
	}
	h := &uploadHandler{hdlr}
	return s.Handle(s.NewHandler(&Upload{h}, opts...))
}

type uploadHandler struct {
	UploadHandler
}

func (h *uploadHandler) WriteImage(ctx context.Context, stream server.Stream) error {
	return h.UploadHandler.WriteImage(ctx, &uploadWriteImageStream{stream})
}

type Upload_WriteImageStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
	Recv() (*Bytes, error)
}

type uploadWriteImageStream struct {
	stream server.Stream
}

func (x *uploadWriteImageStream) Close() error {
	return x.stream.Close()
}

func (x *uploadWriteImageStream) Context() context.Context {
	return x.stream.Context()
}

func (x *uploadWriteImageStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadWriteImageStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadWriteImageStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (x *uploadWriteImageStream) Recv() (*Bytes, error) {
	m := new(Bytes)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *uploadHandler) FileDetail(ctx context.Context, in *FileMate, out *FileMate) error {
	return h.UploadHandler.FileDetail(ctx, in, out)
}
