// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_cs_service_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Response struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.cs.service.auth.Request")
	proto.RegisterType((*Response)(nil), "go.micro.cs.service.auth.Response")
}

func init() {
	proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5)
}

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x3b, 0x4b, 0xc7, 0x30,
	0x14, 0xc5, 0xdb, 0xf8, 0x6a, 0x2f, 0xe8, 0x70, 0x51, 0x28, 0x75, 0xa9, 0x99, 0x3a, 0x45, 0x50,
	0x70, 0x77, 0xea, 0x26, 0x12, 0x15, 0xdc, 0x24, 0xb6, 0x17, 0x1b, 0xa4, 0x49, 0xcd, 0xc3, 0x4f,
	0xe1, 0x87, 0x96, 0xa6, 0x5d, 0x7d, 0x0c, 0xff, 0x25, 0x70, 0x72, 0xee, 0xb9, 0xe7, 0x07, 0x17,
	0xce, 0x66, 0x67, 0x83, 0xbd, 0x54, 0x31, 0x8c, 0xe9, 0x11, 0x49, 0x63, 0xf5, 0x66, 0xc5, 0xa4,
	0x7b, 0x67, 0x45, 0xef, 0x85, 0x27, 0xf7, 0xa9, 0x7b, 0x12, 0x8b, 0xcf, 0x6f, 0xe0, 0x48, 0xd2,
	0x47, 0x24, 0x1f, 0xf0, 0x04, 0x98, 0x1e, 0xaa, 0xbc, 0xc9, 0xdb, 0x3d, 0xc9, 0xf4, 0x80, 0xe7,
	0x50, 0x46, 0x4f, 0xee, 0xc5, 0xa8, 0x89, 0x2a, 0xd6, 0xe4, 0x6d, 0x29, 0x8b, 0xe5, 0xe3, 0x4e,
	0x4d, 0xc4, 0x1b, 0x28, 0x24, 0xf9, 0xd9, 0x1a, 0x4f, 0x78, 0x0a, 0x07, 0xc1, 0xbe, 0x93, 0x49,
	0xd9, 0x52, 0xae, 0xe2, 0xea, 0x8b, 0xc1, 0xfe, 0x6d, 0x0c, 0x23, 0x3e, 0xc3, 0x71, 0x47, 0x86,
	0x9c, 0x0a, 0xf4, 0xb8, 0x38, 0x78, 0x21, 0x7e, 0xc2, 0x11, 0x1b, 0x4b, 0xcd, 0x7f, 0x1b, 0x59,
	0x6b, 0x79, 0x86, 0x4f, 0x00, 0xf7, 0xca, 0xf9, 0x6d, 0xed, 0x3f, 0x32, 0xf5, 0xdf, 0xd5, 0x3c,
	0xc3, 0x07, 0x28, 0x3a, 0x0a, 0xbb, 0x65, 0x7d, 0x3d, 0x4c, 0x97, 0xb8, 0xfe, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x82, 0x98, 0x83, 0x1f, 0xa2, 0x01, 0x00, 0x00,
}
